### ISSUE TITLE
Success rates met pensioeninkomen

### ISSUE THREAD

**Issue by Huppie** [dannyvankooten/dutchfirecalc.nl#16]
Ik zat even met de simulatie te spelen vandaag en kwam iets vreemd tegen wat ik niet helemaal kan verklaren. Ik ben nog niet in de code gedoken, maar misschien valt het wel te beredeneren.  
  
Stel even ik neem een [WR van 6% voor een periode van 20 jaar](https://www.dutchfirecalc.nl/sim?capital=1000000&withdrawal_min=60000&duration=20&minimum_remaining=0&fees=0.15&tax_strategy=vermogensbelasting+2021&aow_amount=&aow_start_year=) dan geeft een slagingspercentage van 73,65%.  
  
Wanneer ik echter de periode opschroef naar 30, 40, 50, of 60 jaar met een pensioeninkomen dat die 60k dekt krijg ik heel andere resultaten, het lijkt bijna random (dat is het niet, I know...) Nu kan ik opzich kleine wijzigingen wel beredeneren simpelweg doordat er minder periodes beschikbaar zijn, maar op een periode van 50 jaar zie je dan bijv. een success rate van 72,5% terwijl je met 60 jaar een success rate van 79% ziet.  
  
Heb jij enig idee wat dit verschil veroorzaakt en waarom het relatief grote verschillen lijkt te veroorzaken?

**Comment by dannyvankooten** [comment]
Het lijkt mij dat de falende runs dan in de afgelopen X jaar zitten waarbij die met duration=X-10 wel meegenomen worden, maar met duration=X niet.

Bijvoorbeeld duration=50 jaar faalt met startjaar 1970. Maar dat startjaar wordt nooit gesimuleerd met duration=60 omdat we geen data tot 2030 hebben.

**Comment by Huppie** [comment]
Ja dat dacht ik eerst ook. Vanuit die gedachte zou ik echter verwachten dat een langere looptijd praktisch gezien altijd een betere success rate op moet leveren wanneer alles > 20 jaar gedekt wordt door pensioeninkomen. Maar je gaat bijv. ook van [25 jaar @ 75% success rate](https://www.dutchfirecalc.nl/sim?capital=1000000&withdrawal_min=60000&duration=25&minimum_remaining=0&fees=0.15&tax_strategy=vermogensbelasting+2021&aow_amount=5000&aow_start_year=2041) naar [45 jaar @ 70% success rate](https://www.dutchfirecalc.nl/sim?capital=1000000&withdrawal_min=60000&duration=45&minimum_remaining=0&fees=0.15&tax_strategy=vermogensbelasting+2021&aow_amount=5000&aow_start_year=2041).  
  
...  
  
Ik zit er nog even naar te kijken en dat komt omdat er simpelweg 375 periodes falen, dat is 25% van 1492 periodes (25 jaar) en 30% van 1250 periodes (45 jaar)
